[build-system]
requires = ["setuptools==80.9.0"]
build-backend = "setuptools.build_meta"

[project]
name = "stackbuilders-hn-crawler"
version = "0.1.0"
description = "An incremental Hacker News HTML crawler hiring exercise."
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = ["beautifulsoup4==4.15.0"]

[project.optional-dependencies]
dev = ["pytest==9.1.1"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--import-mode=importlib"
